openapi: 3.0.2
info:
  title: Simple User API
  version: 1.0.0

paths:
  /users:
    get:
      operationId: listUsers
      summary: List users
      description: Retrieve a paginated list of users.
      parameters:
        - name: limit
          in: query
          description: Maximum number of results to return
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userId:
                      type: string
                    name:
                      type: string
        '400':
          description: Bad Request

  /users/{userId}:
    get:
      operationId: getUserById
      summary: Get user by ID
      description: Retrieve a single user by their unique ID.
      parameters:
        - name: userId
          in: path
          description: ID of the user to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                  name:
                    type: string
        '404':
          description: User Not Found
